/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:ae57fa7e-05e6-457c-823d-4612220296f3",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_9dEHWIQEL",
    "aws_user_pools_web_client_id": "2kkt0p35k159k5u0dnpfmqpibh",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://zlcpvkje4ze63kuzelynhje5pq.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-rxxlbmho3jemtp6so3vzssfgdy",
    "aws_user_files_s3_bucket": "captionthis202153417-staging",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
